[package]
name = "blake3"
version = "0.1.0"
authors = ["Thomas <thomas.jean486@gmail.com>"]

[lib]
name = "blake3"
path = "src/lib.rs"
crate_type = ["cdylib"]

[dependencies]
rustler = ">=0.20.0"
rustler_codegen = ">=0.20.0"
bincode = ">=1.2.0"
blake3 = ">=0.1.0"
