name: CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: OTP ${{matrix.pair.erlang}} / Elixir ${{matrix.pair.elixir}} / Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair:
          - erlang: 21.x
            elixir: 1.x

        rust:
          - 1.41.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Erlang/Elixir
        uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.pair.erlang}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install Rust ${{matrix.rust}} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          override: true

      - name: Run Tests
        run: |
          mix deps.get
          mix test
